name: Deploy to GitHub Pages

on:
  push:
    branches:
      - vue-jy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove package-lock.json and node_modules
        run: |
          rm -f package-lock.json
          rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Check build output for assets
        run: |
          echo "Checking build output for assets..."
          ls -R ./dist/assets
          if [ -z "$(ls -A ./dist/assets)" ]; then
            echo "No assets found in dist/assets directory."
          else
            echo "Assets found in dist/assets directory."
          fi

      - name: Check stores references in build
        run: |
          echo "Checking stores references in build..."
          if grep -r '@/assets' ./dist; then
            echo "Assets references found in build."
          else
            echo "No assets references found in build."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
